# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Continuous Integration Tests

on:
  push:
    branches:
      - main
      - hauboldjonas/ci/add-clang-tidy-checks
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 15 * * *'

jobs:
  beman-submodule-check:
    uses: bemanproject/infra-workflows/.github/workflows/reusable-beman-submodule-check.yml@1.2.1

  preset-test:
    if: false
    uses: bemanproject/infra-workflows/.github/workflows/reusable-beman-preset-test.yml@1.2.1
    with:
      matrix_config: >
        [
          {"preset": "gcc-debug", "image": "ghcr.io/bemanproject/infra-containers-gcc:latest"},
          {"preset": "gcc-release", "image": "ghcr.io/bemanproject/infra-containers-gcc:latest"},
          {"preset": "llvm-debug", "image": "ghcr.io/bemanproject/infra-containers-clang:latest"},
          {"preset": "llvm-release", "image": "ghcr.io/bemanproject/infra-containers-clang:latest"},
          {"preset": "msvc-debug", "runner": "windows-latest"},
          {"preset": "msvc-release", "runner": "windows-latest"}
        ]

  build-and-test:
    if: false
    uses: bemanproject/infra-workflows/.github/workflows/reusable-beman-build-and-test.yml@1.2.1
    with:
      matrix_config: >
        {
          "gcc": [
            { "versions": ["15"],
              "tests": [
                { "cxxversions": ["c++26"],
                  "tests": [
                    { "stdlibs": ["libstdc++"],
                      "tests": [
                        "Debug.Default", "Release.Default",
                        "Release.MaxSan", "Debug.Werror",
                        "Debug.Dynamic", "Debug.Coverage"
                      ]
                    }
                  ]
                },
                { "cxxversions": ["c++23"],
                  "tests": [{ "stdlibs": ["libstdc++"], "tests": ["Release.Default"]}]
                }
              ]
            },
            { "versions": ["14"],
              "tests": [
                { "cxxversions": ["c++26", "c++23"],
                  "tests": [{ "stdlibs": ["libstdc++"], "tests": ["Release.Default"]}]
                }
              ]
            }
          ],
          "clang": [
            { "versions": ["21"],
              "tests": [
                {"cxxversions": ["c++26"],
                  "tests": [
                    { "stdlibs": ["libc++"],
                      "tests": [
                        "Debug.Default", "Release.Default", "Release.MaxSan",
                        "Debug.Dynamic"
                      ]
                    }
                  ]
                },
                { "cxxversions": ["c++23"],
                  "tests": [
                    {"stdlibs": ["libc++"], "tests": ["Release.Default"]}
                  ]
                }
              ]
            },
            { "versions": ["20", "19"],
              "tests": [
                { "cxxversions": ["c++26", "c++23"],
                  "tests": [
                    {"stdlibs": ["libc++"], "tests": ["Release.Default"]}
                  ]
                }
              ]
            }
          ],
          "msvc": [
            { "versions": ["latest"],
              "tests": [
                { "cxxversions": ["c++23"],
                  "tests": [
                    { "stdlibs": ["stl"],
                      "tests": ["Debug.Default", "Release.Default", "Release.MaxSan"]
                    }
                  ]
                }
              ]
            }
          ]
        }

  checkout-and-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bemanproject/infra-containers-clang:latest
    env:
      build_dir: build
      clang_tidy_args: "-config-file=.clang-tidy -checks='-*,bugprone-*'"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & run clang-tidy
        run: |
          cmake -B $build_dir -D CMAKE_CXX_COMPILER=/usr/local/bin/clang -D CMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: clang-tidy src
        run: |
          run-clang-tidy $clang_tidy_args src

      - name: clang-tidy examples
        run: |
          run-clang-tidy $clang_tidy_args examples

  create-issue-when-fault:
    needs: [preset-test, build-and-test]
    if: failure() && github.event_name == 'schedule'
    uses: bemanproject/infra-workflows/.github/workflows/reusable-beman-create-issue-when-fault.yml@1.2.1
